### ISSUE TITLE
Formula zenoh-backend-influxdb doesn't include v2

### ISSUE THREAD

**Issue by fuzzypixelz** [eclipse-zenoh/homebrew-zenoh#6]
[Here](https://github.com/eclipse-zenoh/homebrew-zenoh/blob/main/zenoh-backend-influxdb.rb#L24) only v1 is installed.

**Comment by fuzzypixelz** [comment]
Should we install both versions side by side in the same formula? Or should we make two separate formulae?

**Comment by JEnoch** [comment]
In the same way there are 2 separate Debian packages ([zenoh-backend-influxdb-v1](https://download.eclipse.org/zenoh/debian-repo/0.10.1-rc/zenoh-backend-influxdb-v1_0.10.1-rc-1_amd64.deb) and [zenoh-backend-influxdb-v2](https://download.eclipse.org/zenoh/debian-repo/0.10.1-rc/zenoh-backend-influxdb-v2_0.10.1-rc-1_amd64.deb)), there should be 2 separate formulae.

**Comment by fuzzypixelz** [comment]
Fixed in https://github.com/eclipse-zenoh/homebrew-zenoh/pull/7.
